name: agens

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '27.0'
          elixir-version: '1.17.2'
      - run: mix deps.get
      - run: mix compile --warnings-as-errors --force
      - run: mix format --check-formatted
      - run: mix test
      - run: mix dialyzer
      # - run: mix coveralls.json
      # - name: Upload coverage reports to Codecov
      #   uses: codecov/codecov-action@v3
      #   env:
      #     CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}