name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '28.1'
          elixir-version: '1.19.1'
      - run: mix deps.get
      - run: mix compile --warnings-as-errors --force
      - run: mix format --check-formatted
      - run: mix dialyzer
      - run: mix coveralls.json
      - name: Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}